// The raw list of hooks provided by the user
export const RAW_HOOKS = [
  "1. [número] trucos sobre [tema] que ojalá hubiera sabido antes.",
  "2. Nadie está hablando de esta estrategia de [tema] (y por eso no creces).",
  "3. Por qué tu estrategia de [tema] no te está funcionando (y cómo arreglarla).",
  "4. El hack de [tema] que casi nadie conoce y te da ventaja brutal.",
  "5. Cómo lograr [resultado] sin tener que [cosa que tu audiencia odia hacer].",
  "6. Cómo conseguir [resultado] en solo [tiempo] al día, sin quemarte.",
  "7. Roba esta estrategia que uso para conseguir [resultado] en [tema].",
  "8. [número] movimientos clave para lograr [resultado] con [tema].",
  "9. Cómo logré [resultado concreto] en solo [tiempo] usando esta táctica.",
  "10. Tips de [tema] que casi parecen ilegales de lo bien que funcionan.",
  "11. [número] tips para conseguir [resultado] mucho más rápido con [tema].",
  "12. Errores en [tema] que te están costando [resultado] sin que te des cuenta.",
  "13. [número] señales de que ya estás listo para lograr [resultado] con [tema].",
  "14. Apuesto a que no conocías estos tips de [tema] (y por eso no escalas).",
  "15. Deja de cometer este error con [tema] si quieres crecer de verdad.",
  "16. No vuelvas a [acción que hacen para lograr resultado] antes de hacer esto primero.",
  "17. Deja de [acción típica de tu audiencia] si realmente quieres [resultado].",
  "18. Copia este hack sencillo de [tema] para conseguir [resultado] sin complicarte.",
  "19. La estrategia de [tema] que necesitas conocer antes de seguir publicando.",
  "20. [número] pasos claros para lograr [resultado] con [tema], empezando hoy.",
  "21. Estrategias de [tema] que nadie está comentando pero que dan resultados reales.",
  "22. Errores en [tema] de los que nadie te habla y que frenan tu crecimiento.",
  "23. No cometas estos errores en [tema] si no quieres tirar tu esfuerzo a la basura.",
  "24. La verdadera razón por la que todavía no consigues [resultado] con [tema].",
  "25. Cómo pasar de [situación negativa actual] a [situación positiva deseada] con [tema].",
  "26. [número] red flags en tu estrategia de [tema] que explican por qué no creces.",
  "27. Qué hacer exactamente cuando te pasa [resultado negativo] con [tema].",
  "28. 3 cosas que van a transformar por completo tus resultados con [tema].",
  "29. Por qué dejé de [acción que hacías] para conseguir [resultado] (y qué hago ahora).",
  "30. Deja de [acción que hace tu audiencia]. Te explico por qué te está frenando.",
  "31. Las cosas que hago [frecuencia: cada día/semana] para asegurarme de lograr [resultado].",
  "32. Las mejores estrategias de [tema] que uso para disparar [resultado].",
  "33. [número] señales de que realmente lo estás haciendo bien con [tema].",
  "34. Opinión impopular: hacer [acción positiva típica] puede estar causando [resultado negativo].",
  "35. ¿Estás cometiendo estos errores de [tema] sin darte cuenta?",
  "36. Por qué no necesitas [acción típica] para conseguir [resultado] de verdad.",
  "37. Cómo arreglar ese [resultado negativo] que siempre se repite con [tema].",
  "38. Arregla tu [resultado negativo] en [número] pasos simples (aunque ya lo hayas intentado todo).",
  "39. ¿Te cuesta conseguir [resultado]? Esto es lo que está pasando.",
  "40. Esta es la razón por la que [acción que haces] no te está dando resultados.",
  "41. Cómo dejar de sufrir con [problema/struggle] de una vez por todas.",
  "42. 5 tips fáciles para mejorar tu [tema] hoy mismo.",
  "43. Cómo lograr [resultado] casi al instante con este ajuste en [tema].",
  "44. Este es tu recordatorio para [acción que deberían hacer] si realmente quieres [resultado].",
  "45. [número] razones por las que deberías empezar a [acción concreta] desde hoy.",
  "46. 5 cosas que aprendí intentando conseguir [resultado] (para que no repitas mis errores).",
  "47. ¿Quieres lograr [resultado]? Empieza por esto.",
  "48. Así es como hago [tarea] siendo [identidad/profesión].",
  "49. Deja de [tarea que todos hacen] si de verdad quieres conseguir [resultado].",
  "50. Esto está matando tus resultados con [tema] y casi nadie se da cuenta.",
  "51. Cómo no volver a sufrir [resultado negativo] nunca más con [tema].",
  "52. Todo lo que necesitas saber sobre [tema] en solo [tiempo].",
  "53. [opción] vs [opción] para [tema]… ¿cuál deberías elegir tú?",
  "54. Mis [número] mejores estrategias de [tema] para conseguir [resultado].",
  "55. Por qué [acción específica] es la clave para lograr [resultado].",
  "56. [número] cosas que sí debes hacer y [número] que NO si quieres evitar [resultado negativo] con [tema].",
  "57. El peor tipo de consejos sobre [tema] que terminan llevándote a [resultado negativo].",
  "58. La guía definitiva para dominar [tema] sin perder horas probando al azar.",
  "59. Por qué siempre terminas en [resultado negativo] con [tema] y cómo darle la vuelta a [resultado positivo].",
  "60. [número] errores mortales que debes evitar en [tema] si quieres resultados serios.",
  "61. Qué hacer exactamente cuando te enfrentas otra vez a [resultado negativo] en [tema].",
  "62. Plan de 30 días para lograr [resultado] con [tema] empezando desde cero.",
  "63. Haz esto cada día si quieres conseguir [resultado] con [tema].",
  "64. Cómo hacer que [tema] trabaje para ti, en vez de que tú persigas resultados todo el tiempo.",
  "65. El peor consejo que he escuchado sobre [tema] y por qué deberías ignorarlo.",
  "66. Cómo conseguí [resultado] gracias a [tarea concreta] que casi nadie hace.",
  "67. Pasé de [situación negativa] a [resultado deseado] en [tiempo] usando este enfoque.",
  "68. No vuelvas a [acción típica] antes de hacer primero esto si quieres [resultado].",
  "69. 5 cosas que deberías hacer cuando te pase [resultado negativo] con [tema].",
  "70. ¿Puede [acción que todos recomiendan] estar saboteando tu [resultado deseado]?",
  "71. Esta es la rutina semanal real de un(a) [identidad/profesión] que consigue [resultado].",
  "72. No tienes que [acción típica] para lograr [resultado], y aquí está la prueba.",
  "73. Cómo multiplicar por 5 tus [resultados deseados] en [tiempo] con [tema].",
  "74. 3 cosas que siempre hago antes de [acción] para asegurarme de conseguir [resultado].",
  "75. Tips de [tema] que multiplican por 10 tus resultados si los aplicas bien.",
  "76. Qué tienes que corregir cuando no estás consiguiendo [resultado deseado] con [tema].",
  "77. [número] red flags en tu [tema] que explican por qué no estás creciendo.",
  "78. [número] cosas que deberías saber sobre [tema] antes de seguir creando contenido.",
  "79. ¿Quieres conseguir [resultado] rápido? Mira esto antes de grabar tu próximo video.",
  "80. Un truco simple para mejorar tus [resultados deseados] con [tema] desde hoy.",
  "81. 3 cosas que NUNCA hago si quiero lograr [resultado] con [tema].",
  "82. Si hoy empezara desde cero, este sería mi plan para conseguir [resultado] con [tema].",
  "83. Antes de abandonar [tema], prueba primero esto.",
  "84. La verdad: [tarea que todos creen importante] no es tan clave para lograr [resultado].",
  "85. Cómo conseguir [resultado] este año con [tema] sin complicarte la vida.",
  "86. Si te cuesta conseguir [resultado], mira esto antes de rendirte.",
  "87. [número] reglas de [tema] que guían TODO lo que hago.",
  "88. ¿Atascado en [situación negativa]? Prueba esto en su lugar.",
  "89. Un solo cambio que hizo que empezara a conseguir [resultado].",
  "90. Si no logras [resultado], revisa esto primero.",
  "91. La verdad sobre conseguir [resultado] sin tener que [cosa que la gente odia hacer].",
  "92. Por qué necesitas empezar a [acción clave] si de verdad quieres [resultado].",
  "93. El mejor consejo sobre [tema] que he seguido en mi vida.",
  "94. [número] lecciones que aprendí siendo [identidad/profesión] en [tema].",
  "95. Esta es mi checklist diaria para asegurarme de lograr [resultado].",
  "96. Hacks que todo [identidad/profesión] debería conocer para mejorar en [tema].",
  "97. 3 tips para superar [problema] con [tema] sin perder la cabeza.",
  "98. [número] estrategias de [tema] que ya NO funcionan este año.",
  "99. 5 acciones que deberías añadir a tu [tema] si quieres lograr [resultado].",
  "100. [número] cosas que van a llevarte directo a [resultado negativo] si sigues así con [tema].",
  "101. [número] tips de [tema] que me hicieron pasar de [situación negativa] a [situación positiva].",
  "102. [nombre de estrategia] no es la única forma de conseguir [resultado], y te lo voy a demostrar.",
  "103. Ese consejo típico de “[consejo genérico]” es una mala idea en [tema].",
  "104. Dejé de [tarea que todos hacen] y empecé a conseguir [resultado].",
  "105. Este error está dañando tu [resultado deseado] y casi nadie te lo dice.",
  "106. Esta es la estrategia más rápida que he probado para conseguir [resultado].",
  "107. La forma más fácil de lograr [resultado] con [tema] que realmente funciona.",
  "108. Cómo consigo [resultado] sin tener que [hacer esa cosa que todos odian].",
  "109. Cómo hacer que [tema] trabaje a tu favor en lugar de ser una pérdida de tiempo.",
  "110. Tips de [tema] que vas a desear haber conocido mucho antes.",
  "111. Haz esto cuando te pase [problema] con [tema].",
  "112. Mi guía definitiva para crear una estrategia de [tema] que sí funciona.",
  "113. Cómo diseño una estrategia de [tema] que se convierte en [resultado].",
  "114. 4 formas de garantizar que NO consigas [resultado] con [tema].",
  "115. La mejor estrategia de [tema] para este año si quieres crecer más rápido.",
  "116. Cómo lograr [resultado] incluso cuando estás en plena [situación negativa].",
  "117. Cosas que NO hice y aun así logré [resultado] con [tema].",
  "118. Plan de [número] pasos para no volver a sufrir [problema] nunca más.",
  "119. [número] formas inteligentes de responder cuando te pase [resultado negativo].",
  "120. 3 consejos sobre [tema] de los que nadie habla y que cambian el juego.",
  "121. Probé [acción para lograr resultado] y esto fue lo que pasó de verdad.",
  "122. La verdad detrás de conseguir [resultado] en [tiempo] (no es lo que imaginas).",
  "123. Cómo lograr [resultado] incluso si estás en [situación complicada].",
  "124. El mejor tip para empezar con [tema] aunque seas principiante.",
  "125. Estaba equivocada/o con [tema] y aquí te cuento por qué.",
  "126. Por qué hacer [tarea poco común] es buenísimo para conseguir [resultado].",
  "127. Usé la estrategia de [persona famosa] para conseguir [resultado] y esto pasó.",
  "128. 7 lecciones que aprendí intentando [acción para lograr resultado].",
  "129. Tips de [tema] que cualquier [identidad/profesión] debería aplicar sí o sí.",
  "130. La estrategia de [persona famosa] que usó para lograr [resultado] (y cómo adaptarla).",
  "131. No ignores esta estrategia de [tema] este año si quieres conseguir [resultado].",
  "132. [número] cosas que están matando tus [resultados deseados] con [tema].",
  "133. Multipliqué por 3 mis [resultados deseados] haciendo solo este cambio.",
  "134. Si tuviera que lograr [resultado] desde cero otra vez, haría esto.",
  "135. Cómo conseguí [resultado] gracias a [acción específica que hiciste].",
  "136. Por qué [número]% de las personas fracasan con [tema] y cómo evitarlo.",
  "137. [número] formas de llevar tu estrategia de [tema] al siguiente nivel.",
  "138. Roba esta estrategia sencilla de [tema] para conseguir [resultado] más rápido.",
  "139. La forma antigua vs la nueva de conseguir [resultado] con [tema].",
  "140. [número] recursos clave para dominar [tema] sin perder tiempo.",
  "141. Hacks de [tema] que parecen mentira de lo bien que funcionan.",
  "142. Nunca vuelvas a hacer [tema] sin antes [acción clave] si quieres [resultado].",
  "143. Errores en [tema] que descubrí demasiado tarde (no los repitas).",
  "144. La verdad sobre conseguir [resultado]… no es lo que te han contado.",
  "145. Los [número] mayores mitos sobre [tema] que te están frenando.",
  "146. Tips de [tema] poco valorados de los que nadie habla y que marcan la diferencia.",
  "147. Cómo empezar con [tema] sin tener que pasar por [dolor/pain point].",
  "148. ¿[problema]? Tal vez deberías probar esto primero.",
  "149. “[nombre de estrategia]” está muerta. Haz esto en su lugar si quieres resultados.",
  "150. El peor consejo para empezar con [tema] que escucho todo el tiempo.",
  "151. Evita [acción típica] este año si en serio quieres conseguir [resultado].",
  "152. Cómo hacer que [tema] sea 10 veces más fácil de manejar.",
  "153. Tipos de [tarea/acción] que puedes hacer para lograr [resultado] con [tema].",
  "154. Por qué no necesitas seguir el típico consejo de “[consejo genérico]” en [tema].",
  "155. [número] razones por las que sigues teniendo [problema] con [tema].",
  "156. Deja de hacer [tema] de esta manera si quieres dejar de perder tiempo y dinero.",
  "157. La mejor estrategia de [tema] para ganar este año en tu sector.",
  "158. El verdadero secreto detrás de mis resultados con [tema].",
  "159. [tarea] vs [tarea]… ¿cuál te da mejores resultados de verdad?",
  "160. ¿Vale la pena [tema] este año o ya llegaste tarde?",
  "161. [número] lecciones que necesitas aprender sobre [tema] si quieres mejorar rápido.",
  "162. [número] cosas más importantes que [acción típica] si quieres lograr [resultado].",
  "163. 5 señales de que tu estrategia de [tema] necesita un reset urgente.",
  "164. Has estado haciendo [tema] mal todo este tiempo.",
  "165. No intentes conseguir [resultado] hasta que hagas primero estas cosas.",
  "166. [número] consejos sobre [tema] que cambiaron totalmente mi forma de hacer las cosas.",
  "167. [número] cosas que aprendí por las malas haciendo [tema].",
  "168. No dejes pasar este truco de [tema] si quieres conseguir [resultado].",
  "169. Cómo usar [algo/herramienta/recurso] para lograr [resultado] con [tema].",
  "170. Conseguí muchos más [resultados] con este pequeño ajuste.",
  "171. [número] cosas que deberías dejar de hacer en [tema] ya mismo.",
  "172. [número] reglas de [tema] que necesitas conocer antes de seguir.",
  "173. Por qué hacer [tarea concreta] en realidad está dañando tus [resultados].",
  "174. Cómo convertirte en [identidad/profesión deseada] este año usando [tema].",
  "175. Cómo funciona de verdad [tema] cuando se aplica a [industria/audiencia específica].",
  "176. 5 señales de que estás fallando con [tema] y necesitas cambiar de enfoque.",
  "177. Antes de empezar con [tema], revisa primero esto.",
  "178. Cómo disparar tus [resultados] al instante con un solo ajuste.",
  "179. La estrategia más potente de [tema] para conseguir [resultado].",
  "180. 3 buenas prácticas que usé para lograr [resultado específico].",
  "181. Esto es lo que hice para solucionar [problema] con [tema].",
  "182. Cómo convertir [situación negativa] en [situación positiva] con [tema].",
  "183. Haz estas [número] cosas durante 30 días y vas a ver [resultado].",
  "184. Estrategias de [tema] que puedes probar cuando nada te está funcionando.",
  "185. Estrategias de [tema] que funcionan siempre que las aplicas bien.",
  "186. Mi combo favorito para pasar de [resultado negativo] a [resultado positivo] usando [tema].",
  "187. Conseguí [resultado] en [tiempo] aplicando esto en [tema].",
  "188. La guía definitiva para principiantes que quieren empezar con [tema].",
  "189. [tema] ha cambiado por completo este año y así es como debes adaptarte.",
  "190. Nunca vas a conseguir [resultado] si no haces primero esto.",
  "191. Tendencias de [tema] que deberías probar este año si quieres adelantarte.",
  "192. Cómo logré [resultado] dedicando solo [tiempo] al día a [tema].",
  "193. 3 recursos que uso para llevar mi [tema] al siguiente nivel.",
  "194. ¿Qué pasa si haces [acción para lograr resultado] y no funciona? Aquí la respuesta.",
  "195. Hacer [acción para lograr resultado] no te va a ayudar a conseguir [resultado] y te explico por qué.",
  "196. La mayor mentira sobre [tema] que casi nadie cuestiona.",
  "197. Mis recursos favoritos para lograr [resultado] con [tema] más rápido."
];
